export default {
    appUser:{
        wxLogin:'/api/appUser/wxLogin',
        getWxInfo:'/api/appUser/getWxInfo',
        getWxPhone:'/api/appUser/getWxPhone',
        getMyInfo:'/api/appUser/getMyInfo'
    },
    appOperation:{
        areaIndex:'/api/appOperation/areaIndex',
        queryTemplate:'/api/appOperation/queryTemplate',
        myOrders:'/api/appOperation/myOrders',
        buyTemplate:'/api/appOperation/buyTemplate',
        getUploadPolicy:'/api/appOperation/getUploadPolicy',
        submitVideoPart:'/api/appOperation/submitVideoPart',
        checkOrderPaymentStatus:'/api/appOperation/checkOrderPaymentStatus',
        buyProduct:'/api/appOperation/buyProduct',
        getProductVideo:'/api/appOperation/getProductVideo',
        getWaitingVideo:'/api/appOperation/getWaitingVideo',
        buyVideo:'/api/appOperation/buyVideo'
    }
}
